// TODO: make Serializer.adapter private?
// TODO: make sure UnrecognizedFields and UnrecognizedVariant are generic
// TODO: remove UnrecognizedValues enum, use named parameter for bool
// TODO: figure out what symbols to actually export
// TODO: make them comparable, renderable, etc.
// TODO: KeyedArray...
// TODO: remove all the weird logic which looks at "removed"...
// TODO: rm recursive_default, unrecognized_variant_default, timestamp_defaultake Timestamp much better...
// TODO: move things like StructAdapter to internal...?

import {
  convertCase,
  type CodeGenerator,
  type Constant,
  type Doc,
  type Field,
  type ImportedNames,
  type Method,
  type Module,
  type RecordKey,
  type RecordLocation,
  type ResolvedType,
} from "skir-internal";
import { z } from "zod";
import {
  KeyedArrayContext,
  keyTypeIsSupported,
} from "./keyed_array_context.js";
import {
  getTypeName,
  modulePathToAlias,
  modulePathToFileStem,
  modulePathToPackageDir,
  toEnumVariantName,
  toStructFieldName,
} from "./naming.js";
import { TypeSpeller } from "./type_speller.js";

const Config = z.strictObject({});

type Config = z.infer<typeof Config>;

class MoonbitCodeGenerator implements CodeGenerator<Config> {
  readonly id = "skir-moonbit-gen";
  readonly configType = Config;

  generateCode(input: CodeGenerator.Input<Config>): CodeGenerator.Output {
    const { recordMap } = input;
    const keyedArrayContext = new KeyedArrayContext(input.modules);
    const outputFiles: CodeGenerator.OutputFile[] = [];
    for (const module of input.modules) {
      const packageDir = modulePathToPackageDir(module.path);
      const fileStem = modulePathToFileStem(module.path);
      outputFiles.push({
        path: `${packageDir}/moon.pkg`,
        code: generateMoonPkg(module),
      });
      outputFiles.push({
        path: `${packageDir}/${fileStem}.mbt`,
        code: new MoonbitSourceFileGenerator(
          module,
          recordMap,
          keyedArrayContext,
        ).generate(),
      });
    }
    return { files: outputFiles };
  }
}

class MoonbitSourceFileGenerator {
  constructor(
    private readonly inModule: Module,
    recordMap: ReadonlyMap<RecordKey, RecordLocation>,
    private readonly keyedArrayContext: KeyedArrayContext,
  ) {
    this.typeSpeller = new TypeSpeller(recordMap, inModule.path);
  }

  generate(): string {
    const out: string[] = [];

    out.push(
      "//  ______                        _               _  _  _\n",
      "//  |  _  \\                      | |             | |(_)| |\n",
      "//  | | | |  ___    _ __    ___  | |_    ___   __| | _ | |_\n",
      "//  | | | | / _ \\  | '_ \\  / _ \\ | __|  / _ \\ / _` || || __|\n",
      "//  | |/ / | (_) | | | | || (_) || |_  |  __/| (_| || || |_ \n",
      "//  |___/   \\___/  |_| |_| \\___/  \\__|  \\___| \\__,_||_| \\__|\n",
      "//\n",
      "// Generated by skir-moonbit-gen\n\n",
    );

    for (const record of this.inModule.records) {
      this.writeRecord(record, out);
    }

    for (const constant of this.inModule.constants) {
      this.writeConstant(constant, out);
    }

    for (const method of this.inModule.methods) {
      this.writeMethod(method, out);
    }

    if (this.initStatements.length > 0) {
      out.push("fn init {\n");
      for (const statement of this.initStatements) {
        out.push(`  ${statement}\n`);
      }
      out.push("}\n\n");
    }

    return out.join("");
  }

  private writeRecord(record: RecordLocation, out: string[]): void {
    const recordType = record.record.recordType;
    const typeName = this.getTypeName(record);

    out.push(`// ${recordType} ${typeName}\n`);
    if (recordType === "struct") {
      this.writeStruct(record, out);
    } else {
      this.writeEnum(record, out);
    }
  }

  private getTypeName(record: RecordLocation): string {
    return getTypeName(record);
  }

  private writeConstant(constant: Constant, out: string[]): void {
    if (!constant.type || constant.valueAsDenseJson === undefined) {
      return;
    }
    const moonbitName = `${convertCase(constant.name.text, "lower_underscore")}_const`;
    const moonbitType = this.typeSpeller.getMoonbitType(constant.type);
    const serializerExpr = this.getSerializerExpr(constant.type);
    const jsonLiteral = this.toMoonbitStringLiteral(
      JSON.stringify(constant.valueAsDenseJson),
    );
    out.push(`pub let ${moonbitName} : ${moonbitType} =\n`);
    out.push(
      `  match ${serializerExpr}.from_json(${jsonLiteral}, @client.unrecognized_values_drop()) {\n`,
    );
    out.push("    Ok(value) => value\n");
    out.push("    Err(_) => panic()\n");
    out.push("  }\n\n");
  }

  private writeStruct(record: RecordLocation, out: string[]): void {
    const fields = record.record.fields;
    const removedNumbers = record.record.removedNumbers;
    const typeName = this.getTypeName(record);
    const adapterVarName = `${typeName.toLowerCase()}__adapter`;
    const isRecursive = this.isRecursiveRecord(fields);
    const recordIdLiteral = this.toMoonbitStringLiteral(
      `${record.modulePath}:${record.recordAncestors.map((ancestor) => ancestor.name.text).join(".")}`,
    );
    const recordDocLiteral = this.toMoonbitStringLiteral(
      docToCommentText(record.record.doc),
    );
    const structFieldNames = fields.map((field) =>
      toStructFieldName(field.name.text),
    );
    let copySelfName = "self";
    while (structFieldNames.includes(copySelfName)) {
      copySelfName = `${copySelfName}_`;
    }

    out.push(`pub struct ${typeName} {\n`);
    for (const field of fields) {
      const fieldName = toStructFieldName(field.name.text);
      const moonbitType = this.typeSpeller.getMoonbitFieldType(field);
      out.push(`  mut ${fieldName} : ${moonbitType}\n`);
    }
    out.push("  priv mut _unrecognized : @client.UnrecognizedFields?\n");
    out.push("} derive(@builtin.Eq, @debug.Debug)\n\n");

    out.push(`pub fn ${typeName}::new(`);
    if (fields.length > 0) {
      out.push("\n");
      for (const field of fields) {
        const fieldName = toStructFieldName(field.name.text);
        const moonbitType = this.typeSpeller.getMoonbitFieldType(field);
        out.push(`  ${fieldName}~ : ${moonbitType},\n`);
      }
    }
    out.push(`) -> ${typeName} {\n`);
    out.push("  {\n");
    for (const field of fields) {
      const fieldName = toStructFieldName(field.name.text);
      out.push(`    ${fieldName},\n`);
    }
    out.push("    _unrecognized: None,\n");
    out.push("  }\n");
    out.push("}\n\n");

    out.push(`pub fn ${typeName}::partial(`);
    if (fields.length > 0) {
      out.push("\n");
      for (const field of fields) {
        const fieldName = toStructFieldName(field.name.text);
        const moonbitType = this.typeSpeller.getMoonbitFieldType(field);
        const defaultValue = this.typeSpeller.getMoonbitFieldDefault(field);
        out.push(`  ${fieldName}~ : ${moonbitType}=${defaultValue},\n`);
      }
    }
    out.push(`) -> ${typeName} {\n`);
    if (fields.length === 0) {
      out.push(`  ${typeName}::new()\n`);
    } else {
      out.push(`  ${typeName}::new(\n`);
      for (const field of fields) {
        const fieldName = toStructFieldName(field.name.text);
        out.push(`    ${fieldName}=${fieldName},\n`);
      }
      out.push("  )\n");
    }
    out.push("}\n\n");

    out.push(`pub fn ${typeName}::copy(\n`);
    out.push(`  ${copySelfName} : ${typeName},\n`);
    for (const field of fields) {
      const fieldName = toStructFieldName(field.name.text);
      const moonbitType = this.typeSpeller.getMoonbitFieldType(field);
      out.push(
        `  ${fieldName}~ : @client.KeepOrSet[${moonbitType}]=@client.keep_or_set_keep(),\n`,
      );
    }
    out.push(`) -> ${typeName} {\n`);
    out.push("  {\n");
    for (const field of fields) {
      const fieldName = toStructFieldName(field.name.text);
      out.push(`    ${fieldName}: match ${fieldName} {\n`);
      out.push(`      @client.KeepOrSet::Keep => ${copySelfName}.`);
      out.push(`${fieldName}\n`);
      out.push("      @client.KeepOrSet::Set(value) => value\n");
      out.push("    },\n");
    }
    out.push(`    _unrecognized: ${copySelfName}._unrecognized,\n`);
    out.push("  }\n");
    out.push("}\n\n");

    out.push(`pub fn ${typeName}::default() -> ${typeName} {\n`);
    if (fields.length === 0) {
      out.push(`  ${typeName}::new()\n`);
    } else {
      out.push(`  ${typeName}::new(\n`);
      for (const field of fields) {
        const fieldName = toStructFieldName(field.name.text);
        const defaultValue = this.typeSpeller.getMoonbitFieldDefault(field);
        out.push(`    ${fieldName}=${defaultValue},\n`);
      }
      out.push("  )\n");
    }
    out.push("}\n\n");

    if (isRecursive) {
      out.push(
        `let ${adapterVarName} : @runtime.StructAdapter[${typeName}] = @runtime.StructAdapter::new(\n`,
      );
      out.push(`  ${recordIdLiteral},\n`);
      out.push('  "",\n');
      out.push(`  ${recordDocLiteral},\n`);
      out.push(`  fn() { ${typeName}::default() },\n`);
      out.push(`  fn(input : ${typeName}) { input._unrecognized },\n`);
      out.push(
        `  fn(input : ${typeName}, value : @client.UnrecognizedFields?) {\n`,
      );
      out.push("    input._unrecognized = value\n");
      out.push("  },\n");
      out.push(")\n\n");

      for (const field of fields) {
        this.initStatements.push(
          ...this.getStructAddFieldLines(typeName, adapterVarName, field),
        );
      }
      for (const number of removedNumbers) {
        this.initStatements.push(
          `${adapterVarName}.add_removed_number(${number})`,
        );
      }
      this.initStatements.push(`${adapterVarName}.finalize()`);

      out.push(
        `pub fn ${typeName}::serializer() -> @runtime.Serializer[${typeName}] {\n`,
      );
      out.push(`  ${adapterVarName}.serializer()\n`);
      out.push("}\n\n");
    } else {
      const adapterInitFnName = `${adapterVarName}__init`;
      out.push(
        `pub fn ${typeName}::serializer() -> @runtime.Serializer[${typeName}] {\n`,
      );
      out.push(`  ${adapterVarName}.serializer()\n`);
      out.push("}\n\n");

      out.push(
        `let ${adapterVarName} : @runtime.StructAdapter[${typeName}] = ${adapterInitFnName}()\n\n`,
      );

      out.push(
        `fn ${adapterInitFnName}() -> @runtime.StructAdapter[${typeName}] {\n`,
      );
      out.push("  let adapter = @runtime.StructAdapter::new(\n");
      out.push(`    ${recordIdLiteral},\n`);
      out.push('    "",\n');
      out.push(`    ${recordDocLiteral},\n`);
      out.push(`    fn() { ${typeName}::default() },\n`);
      out.push(`    fn(input : ${typeName}) { input._unrecognized },\n`);
      out.push(
        `    fn(input : ${typeName}, value : @client.UnrecognizedFields?) {\n`,
      );
      out.push("      input._unrecognized = value\n");
      out.push("    },\n");
      out.push("  )\n");

      for (const field of fields) {
        for (const line of this.getStructAddFieldLines(
          typeName,
          "adapter",
          field,
        )) {
          out.push(`  ${line}\n`);
        }
      }
      for (const number of removedNumbers) {
        out.push(`  adapter.add_removed_number(${number})\n`);
      }
      out.push("  adapter.finalize()\n");
      out.push("  adapter\n");
      out.push("}\n\n");
    }

    this.writeKeyedVectorWrappers(record, typeName, out);
  }

  private writeEnum(record: RecordLocation, out: string[]): void {
    const variants = record.record.fields;
    const removedNumbers = record.record.removedNumbers;
    const typeName = this.getTypeName(record);
    const unknownVarName = `${typeName.toLowerCase()}__unknown`;
    const adapterVarName = `${typeName.toLowerCase()}__adapter`;
    const isRecursive = this.isRecursiveRecord(variants);
    const recordIdLiteral = this.toMoonbitStringLiteral(
      `${record.modulePath}:${record.recordAncestors.map((ancestor) => ancestor.name.text).join(".")}`,
    );
    const recordDocLiteral = this.toMoonbitStringLiteral(
      docToCommentText(record.record.doc),
    );

    out.push(`pub(all) enum ${typeName} {\n`);
    const usedNames = new Set<string>();
    usedNames.add("Unknown");
    out.push("  Unknown(@client.UnrecognizedVariant)\n");
    const variantNames: Array<{
      field: Field;
      hasPayload: boolean;
      variantName: string;
    }> = [];
    for (const variant of variants) {
      const variantName = toEnumVariantName(variant.name.text, usedNames);
      usedNames.add(variantName);
      variantNames.push({
        field: variant,
        hasPayload: !!variant.type,
        variantName,
      });
      if (variant.type) {
        const variantType = this.typeSpeller.getMoonbitType(variant.type);
        out.push(`  ${variantName}(${variantType})\n`);
      } else {
        out.push(`  ${variantName}\n`);
      }
    }
    out.push("} derive(@builtin.Eq, @debug.Debug)\n\n");

    out.push(`let ${unknownVarName} : ${typeName} = `);
    out.push(
      `${typeName}::Unknown(@client.unrecognized_variant_default())\n\n`,
    );

    out.push(`pub fn ${typeName}::unknown() -> ${typeName} {\n`);
    out.push(`  ${unknownVarName}\n`);
    out.push("}\n\n");

    const addVariantLines: string[] = [];
    let kindOrdinal = 1;
    for (const variant of variantNames) {
      const number = variant.field.number;
      const nameLiteral = this.toMoonbitStringLiteral(variant.field.name.text);
      if (!variant.field.type) {
        addVariantLines.push(
          `${adapterVarName}.add_constant_variant(${nameLiteral}, ${number}, ${kindOrdinal}, ${toMoonbitStringLiteral(docToCommentText(variant.field.doc))}, ${typeName}::${variant.variantName})`,
        );
      } else {
        const resolvedType = variant.field.type;
        const isKeyedArrayVariant =
          resolvedType.kind === "array" &&
          !!resolvedType.key &&
          keyTypeIsSupported(resolvedType.key.keyType);
        const serializerExpr = this.getSerializerExpr(resolvedType);

        let valueType = this.typeSpeller.getMoonbitType(resolvedType);
        let wrappedValueExpr = "value";
        let extractedValueExpr = "value";
        let defaultValueExpr = this.typeSpeller.getMoonbitDefault(resolvedType);

        if (isKeyedArrayVariant) {
          const itemType = this.typeSpeller.getMoonbitType(resolvedType.item);
          const wrapperType = this.typeSpeller.getMoonbitType(resolvedType);
          valueType = `@client.Vector[${itemType}]`;
          wrappedValueExpr = `${wrapperType}::new(value)`;
          extractedValueExpr = "value.vector()";
          defaultValueExpr = `${defaultValueExpr}.vector()`;
        }

        addVariantLines.push(
          `${adapterVarName}.add_wrapper_variant(${nameLiteral}, ${number}, ${kindOrdinal}, ${serializerExpr}, ${toMoonbitStringLiteral(docToCommentText(variant.field.doc))}, fn(value : ${valueType}) { ${typeName}::${variant.variantName}(${wrappedValueExpr}) }, fn(input : ${typeName}) { if input is ${typeName}::${variant.variantName}(value) { ${extractedValueExpr} } else { ${defaultValueExpr} } })`,
        );
      }
      kindOrdinal = kindOrdinal + 1;
    }

    if (isRecursive) {
      out.push(
        `let ${adapterVarName} : @runtime.EnumAdapter[${typeName}] = @runtime.EnumAdapter::new(\n`,
      );
      out.push(`  ${recordIdLiteral},\n`);
      out.push('  "",\n');
      out.push(`  ${recordDocLiteral},\n`);
      out.push(`  ${unknownVarName},\n`);
      out.push(`  fn(input : ${typeName}) {\n`);
      out.push("    match input {\n");
      out.push(`      ${typeName}::Unknown(_) => 0\n`);
      kindOrdinal = 1;
      for (const variant of variantNames) {
        if (variant.hasPayload) {
          out.push(
            `      ${typeName}::${variant.variantName}(_) => ${kindOrdinal}\n`,
          );
        } else {
          out.push(
            `      ${typeName}::${variant.variantName} => ${kindOrdinal}\n`,
          );
        }
        kindOrdinal = kindOrdinal + 1;
      }
      out.push("    }\n");
      out.push("  },\n");
      out.push(
        `  fn(value : @client.UnrecognizedVariant) { ${typeName}::Unknown(value) },\n`,
      );
      out.push(`  fn(input : ${typeName}) {\n`);
      out.push("    match input {\n");
      out.push(`      ${typeName}::Unknown(value) => Some(value)\n`);
      if (variantNames.length > 0) {
        out.push("      _ => None\n");
      }
      out.push("    }\n");
      out.push("  },\n");
      out.push(")\n\n");

      for (const line of addVariantLines) {
        this.initStatements.push(line);
      }
      for (const number of removedNumbers) {
        this.initStatements.push(
          `${adapterVarName}.add_removed_number(${number})`,
        );
      }
      this.initStatements.push(`${adapterVarName}.finalize()`);
    } else {
      const adapterInitFnName = `${adapterVarName}__init`;
      out.push(
        `fn ${adapterInitFnName}() -> @runtime.EnumAdapter[${typeName}] {\n`,
      );
      out.push("  let adapter = @runtime.EnumAdapter::new(\n");
      out.push(`    ${recordIdLiteral},\n`);
      out.push('    "",\n');
      out.push(`    ${recordDocLiteral},\n`);
      out.push(`    ${unknownVarName},\n`);
      out.push(`    fn(input : ${typeName}) {\n`);
      out.push("      match input {\n");
      out.push(`        ${typeName}::Unknown(_) => 0\n`);
      kindOrdinal = 1;
      for (const variant of variantNames) {
        if (variant.hasPayload) {
          out.push(
            `        ${typeName}::${variant.variantName}(_) => ${kindOrdinal}\n`,
          );
        } else {
          out.push(
            `        ${typeName}::${variant.variantName} => ${kindOrdinal}\n`,
          );
        }
        kindOrdinal = kindOrdinal + 1;
      }
      out.push("      }\n");
      out.push("    },\n");
      out.push(
        `    fn(value : @client.UnrecognizedVariant) { ${typeName}::Unknown(value) },\n`,
      );
      out.push(`    fn(input : ${typeName}) {\n`);
      out.push("      match input {\n");
      out.push(`        ${typeName}::Unknown(value) => Some(value)\n`);
      if (variantNames.length > 0) {
        out.push("        _ => None\n");
      }
      out.push("      }\n");
      out.push("    },\n");
      out.push("  )\n");
      for (const line of addVariantLines) {
        out.push(`  ${line.replace(adapterVarName, "adapter")}\n`);
      }
      for (const number of removedNumbers) {
        out.push(`  adapter.add_removed_number(${number})\n`);
      }
      out.push("  adapter.finalize()\n");
      out.push("  adapter\n");
      out.push("}\n\n");

      out.push(
        `let ${adapterVarName} : @runtime.EnumAdapter[${typeName}] = ${adapterInitFnName}()\n\n`,
      );
    }

    out.push(
      `pub fn ${typeName}::serializer() -> @runtime.Serializer[${typeName}] {\n`,
    );
    out.push(`  ${adapterVarName}.serializer()\n`);
    out.push("}\n\n");

    if (this.keyedArrayContext.isEnumUsedAsKey(record.record)) {
      out.push(`pub(all) enum ${typeName}_kind {\n`);
      out.push("  Unknown\n");
      for (const variant of variantNames) {
        out.push(`  ${variant.variantName}\n`);
      }
      out.push("} derive(@builtin.Eq, @builtin.Hash, @debug.Debug)\n\n");

      out.push(
        `pub fn ${typeName}::kind(self : ${typeName}) -> ${typeName}_kind {\n`,
      );
      out.push("  match self {\n");
      out.push(`    ${typeName}::Unknown(_) => ${typeName}_kind::Unknown\n`);
      for (const variant of variantNames) {
        if (variant.hasPayload) {
          out.push(
            `    ${typeName}::${variant.variantName}(_) => ${typeName}_kind::${variant.variantName}\n`,
          );
        } else {
          out.push(
            `    ${typeName}::${variant.variantName} => ${typeName}_kind::${variant.variantName}\n`,
          );
        }
      }
      out.push("  }\n");
      out.push("}\n\n");
    }
  }

  private writeMethod(method: Method, out: string[]): void {
    if (!method.requestType || !method.responseType) {
      return;
    }

    const methodName = `${convertCase(method.name.text, "lower_underscore")}_method`;
    const requestType = this.typeSpeller.getMoonbitType(method.requestType);
    const responseType = this.typeSpeller.getMoonbitType(method.responseType);
    const requestSerializer = this.typeSpeller.getMoonbitSerializerExpr(
      method.requestType,
    );
    const responseSerializer = this.typeSpeller.getMoonbitSerializerExpr(
      method.responseType,
    );

    out.push(commentify(docToCommentText(method.doc)));
    out.push(
      `pub fn ${methodName}() -> @client.Method[${requestType}, ${responseType}] {\n`,
    );
    out.push("  {\n");
    out.push(`    name: ${toMoonbitStringLiteral(method.name.text)},\n`);
    out.push(`    number: ${method.number},\n`);
    out.push(`    request_serializer: ${requestSerializer},\n`);
    out.push(`    response_serializer: ${responseSerializer},\n`);
    out.push(`    doc: ${toMoonbitStringLiteral(docToCommentText(method.doc))},\n`);
    out.push("  }\n");
    out.push("}\n\n");
  }

  private writeKeyedVectorWrappers(
    record: RecordLocation,
    typeName: string,
    out: string[],
  ): void {
    const keySpecs = this.keyedArrayContext.getKeySpecsForItemStruct(
      record.record,
      this.typeSpeller,
    );

    for (const keySpec of keySpecs) {
      const wrapperTypeName = `${typeName}${keySpec.moonbitTypeSuffix}`;
      const specVarName = `${wrapperTypeName.toLowerCase()}__spec`;

      out.push(
        `let ${specVarName} : @client.KeyedVectorSpec[${typeName}, ${keySpec.moonbitKeyType}] = {\n`,
      );
      out.push(
        `  get_key: fn(item : ${typeName}) { ${keySpec.moonbitKeyExpr} },\n`,
      );
      out.push(`  key_extractor: "${keySpec.keyExtractor}",\n`);
      out.push(`  default_item: ${typeName}::default(),\n`);
      out.push("}\n\n");

      const methodSuffix = keySpec.keyExtractor.replace(/\./g, "_");

      out.push(`pub struct ${wrapperTypeName} {
`);
      out.push(
        `  priv vector : @client.KeyedVector[${typeName}, ${keySpec.moonbitKeyType}]\n`,
      );
      out.push("} derive(@builtin.Eq, @debug.Debug)\n\n");

      out.push(
        `pub fn ${wrapperTypeName}::vector(self : ${wrapperTypeName}) -> @client.Vector[${typeName}] {\n`,
      );
      out.push("  self.vector.vector\n");
      out.push("}\n\n");

      out.push(
        `pub fn ${wrapperTypeName}::new(vector : @client.Vector[${typeName}]) -> ${wrapperTypeName} {\n`,
      );
      out.push(
        `  { vector: @client.KeyedVector::new(vector, ${specVarName}) }\n`,
      );
      out.push("}\n\n");

      out.push(
        `pub fn ${wrapperTypeName}::from_array(items : Array[${typeName}]) -> ${wrapperTypeName} {\n`,
      );
      out.push(
        `  { vector: @client.KeyedVector::from_array(items, ${specVarName}) }\n`,
      );
      out.push("}\n\n");

      out.push(`pub fn ${wrapperTypeName}::empty() -> ${wrapperTypeName} {\n`);
      out.push(`  { vector: @client.KeyedVector::empty(${specVarName}) }\n`);
      out.push("}\n\n");

      out.push(
        `pub fn ${wrapperTypeName}::find_by_${methodSuffix}(self : ${wrapperTypeName}, key : ${keySpec.moonbitKeyType}) -> ${typeName}? {\n`,
      );
      out.push("  self.vector.find_by_key(key)\n");
      out.push("}\n\n");

      out.push(
        `pub fn ${wrapperTypeName}::find_by_${methodSuffix}_or_default(self : ${wrapperTypeName}, key : ${keySpec.moonbitKeyType}) -> ${typeName} {\n`,
      );
      out.push("  self.vector.find_by_key_or_default(key)\n");
      out.push("}\n\n");
    }
  }

  private isRecursiveRecord(fields: readonly Field[]): boolean {
    return fields.some((field) => !!field.isRecursive);
  }

  private getRecordNamespace(): string {
    return this.inModule.path.replace(/\.skir$/, "").replace(/\//g, ".");
  }

  private toMoonbitStringLiteral(value: string): string {
    return JSON.stringify(value);
  }

  private getSerializerExpr(type: ResolvedType): string {
    switch (type.kind) {
      case "primitive": {
        switch (type.primitive) {
          case "bool":
            return "@runtime.bool_serializer()";
          case "int32":
            return "@runtime.int32_serializer()";
          case "int64":
            return "@runtime.int64_serializer()";
          case "hash64":
            return "@runtime.hash64_serializer()";
          case "float32":
            return "@runtime.float32_serializer()";
          case "float64":
            return "@runtime.float64_serializer()";
          case "timestamp":
            return "@runtime.timestamp_serializer()";
          case "string":
            return "@runtime.string_serializer()";
          case "bytes":
            return "@runtime.bytes_serializer()";
        }
        throw new Error(`Unsupported primitive serializer: ${type.primitive}`);
      }
      case "optional":
        return `@runtime.optional_serializer(${this.getSerializerExpr(type.other)})`;
      case "array":
        return `@runtime.vector_serializer(${this.getSerializerExpr(type.item)})`;
      case "record": {
        const recordLocation = this.typeSpeller.recordMap.get(type.key)!;
        const recordTypeName = getTypeName(recordLocation);
        if (recordLocation.modulePath === this.inModule.path) {
          return `${recordTypeName}::serializer()`;
        }
        return `@${modulePathToAlias(recordLocation.modulePath)}.${recordTypeName}::serializer()`;
      }
    }
  }

  private getStructAddFieldLines(
    typeName: string,
    adapterVarName: string,
    field: Field,
  ): string[] {
    const fieldName = toStructFieldName(field.name.text);
    const resolvedType = field.type!;
    const isKeyedArrayField =
      resolvedType.kind === "array" &&
      !!resolvedType.key &&
      keyTypeIsSupported(resolvedType.key.keyType);

    const serializerExpr =
      field.isRecursive === "hard"
        ? `@runtime.recursive_serializer(${this.getSerializerExpr(resolvedType)})`
        : isKeyedArrayField
          ? `@runtime.keyed_vector_serializer(${this.getSerializerExpr(resolvedType.item)}, ${this.toMoonbitStringLiteral(resolvedType.key!.path.map((part) => part.name.text).join("."))})`
          : this.getSerializerExpr(resolvedType);

    const normalFieldType = this.typeSpeller.getMoonbitFieldType(field);
    let setterValueType = normalFieldType;
    let getterExpr = `input.${fieldName}`;
    let setterExpr = "value";
    if (isKeyedArrayField) {
      const itemType = this.typeSpeller.getMoonbitType(resolvedType.item);
      const wrapperType = this.typeSpeller.getMoonbitType(resolvedType);
      setterValueType = `@client.Vector[${itemType}]`;
      getterExpr = `input.${fieldName}.vector()`;
      setterExpr = `${wrapperType}::new(value)`;
    }

    const lines: string[] = [];
    lines.push(`${adapterVarName}.add_field(`);
    lines.push(`  ${this.toMoonbitStringLiteral(field.name.text)},`);
    lines.push(`  ${field.number},`);
    lines.push(`  ${serializerExpr},`);
    lines.push(`  fn(input : ${typeName}) { ${getterExpr} },`);
    lines.push(`  fn(input : ${typeName}, value : ${setterValueType}) {`);
    lines.push(`    input.${fieldName} = ${setterExpr}`);
    lines.push("  },");
    lines.push(
      `  ${this.toMoonbitStringLiteral(docToCommentText(field.doc))},`,
    );
    lines.push(")");
    return lines;
  }

  private readonly typeSpeller: TypeSpeller;
  private readonly initStatements: string[] = [];
}

export const GENERATOR = new MoonbitCodeGenerator();

function generateMoonPkg(module: Module): string {
  const imports: string[] = [];
  imports.push(`  "${CLIENT_PACKAGE_PATH}" @client,`);
  imports.push(`  "${CLIENT_RUNTIME_PACKAGE_PATH}" @runtime,`);
  imports.push(`  "moonbitlang/core/builtin" @builtin,`);
  imports.push(`  "moonbitlang/core/debug" @debug,`);

  for (const [importedPath, importedNames] of Object.entries(
    module.pathToImportedNames,
  )) {
    if (!shouldImportModule(importedNames)) {
      continue;
    }
    const alias = modulePathToAlias(importedPath);
    const packageDir = modulePathToPackageDir(importedPath);
    imports.push(`  "${SKIROUT_PACKAGE_PREFIX}/${packageDir}" @${alias},`);
  }

  return `import {\n${imports.join("\n")}\n}\n`;
}

function shouldImportModule(importedNames: ImportedNames): boolean {
  return importedNames.kind === "all" || importedNames.names.size > 0;
}

function commentify(textOrLines: string | readonly string[]): string {
  const text = (
    typeof textOrLines === "string" ? textOrLines : textOrLines.join("\n")
  )
    .trim()
    .replace(/\n{3,}/g, "\n\n");
  if (text.length <= 0) {
    return "";
  }
  return text
    .split("\n")
    .map((line) => (line.length > 0 ? `/// ${line}\n` : "///\n"))
    .join("");
}

function docToCommentText(doc: Doc): string {
  return doc.pieces
    .map((piece) => {
      switch (piece.kind) {
        case "text":
          return piece.text;
        case "reference":
          return `\`${piece.referenceRange.text.slice(1, -1)}\``;
      }
    })
    .join("");
}

function toMoonbitStringLiteral(value: string): string {
  return JSON.stringify(value);
}

const SKIROUT_PACKAGE_PREFIX = "skir/e2e-tests/skirout";
const CLIENT_PACKAGE_PATH = "skir/e2e-tests/client/types";
const CLIENT_RUNTIME_PACKAGE_PATH = "skir/e2e-tests/client";
