// TODO: make sure that pre_commit.sh formats
// TODO: make sure UnrecognizedFields and UnrecognizedVariant are generic
// TODO: make them comparable, renderable, etc.
// TODO: KeyedArray...
// TODO: make Timestamp much better...

import {
  type CodeGenerator,
  type Field,
  type ImportedNames,
  type Module,
  type RecordKey,
  type RecordLocation,
} from "skir-internal";
import { z } from "zod";
import {
  getTypeName,
  modulePathToAlias,
  modulePathToFileStem,
  modulePathToPackageDir,
  toEnumVariantName,
  toStructFieldName,
} from "./naming.js";
import { TypeSpeller } from "./type_speller.js";

const Config = z.strictObject({});

type Config = z.infer<typeof Config>;

class MoonbitCodeGenerator implements CodeGenerator<Config> {
  readonly id = "skir-moonbit-gen";
  readonly configType = Config;

  generateCode(input: CodeGenerator.Input<Config>): CodeGenerator.Output {
    const { recordMap } = input;
    const outputFiles: CodeGenerator.OutputFile[] = [];
    for (const module of input.modules) {
      const packageDir = modulePathToPackageDir(module.path);
      const fileStem = modulePathToFileStem(module.path);
      outputFiles.push({
        path: `${packageDir}/moon.pkg`,
        code: generateMoonPkg(module),
      });
      outputFiles.push({
        path: `${packageDir}/${fileStem}.mbt`,
        code: new MoonbitSourceFileGenerator(module, recordMap).generate(),
      });
    }
    return { files: outputFiles };
  }
}

class MoonbitSourceFileGenerator {
  constructor(
    private readonly inModule: Module,
    recordMap: ReadonlyMap<RecordKey, RecordLocation>,
  ) {
    this.typeSpeller = new TypeSpeller(recordMap, inModule.path);
  }

  generate(): string {
    const out: string[] = [];

    out.push(
      "//  ______                        _               _  _  _\n",
      "//  |  _  \\                      | |             | |(_)| |\n",
      "//  | | | |  ___    _ __    ___  | |_    ___   __| | _ | |_\n",
      "//  | | | | / _ \\  | '_ \\  / _ \\ | __|  / _ \\ / _` || || __|\n",
      "//  | |/ / | (_) | | | | || (_) || |_  |  __/| (_| || || |_ \n",
      "//  |___/   \\___/  |_| |_| \\___/  \\__|  \\___| \\__,_||_| \\__|\n",
      "//\n",
      "// Generated by skir-moonbit-gen\n\n",
    );

    for (const record of this.inModule.records) {
      this.writeRecord(record, out);
    }

    return out.join("");
  }

  private writeRecord(record: RecordLocation, out: string[]): void {
    const recordType = record.record.recordType;
    const typeName = this.getTypeName(record);

    out.push(`// ${recordType} ${typeName}\n`);
    if (recordType === "struct") {
      this.writeStruct(record, out);
    } else {
      this.writeEnum(record, out);
    }
  }

  private getTypeName(record: RecordLocation): string {
    return getTypeName(record);
  }

  private writeStruct(record: RecordLocation, out: string[]): void {
    const fields = this.getPresentFields(record.record.fields);
    const typeName = this.getTypeName(record);
    const defaultVarName = `${typeName.toLowerCase()}__default`;

    out.push(`pub struct ${typeName} {\n`);
    for (const field of fields) {
      const fieldName = toStructFieldName(field.name.text);
      const moonbitType = this.typeSpeller.getMoonbitFieldType(field);
      out.push(`  ${fieldName} : ${moonbitType}\n`);
    }
    out.push("  _unrecognized : @client.UnrecognizedFields?\n");
    out.push("}\n\n");

    out.push(`let ${defaultVarName} : ${typeName} = {\n`);
    for (const field of fields) {
      const fieldName = toStructFieldName(field.name.text);
      const defaultValue = this.typeSpeller.getMoonbitFieldDefault(field);
      out.push(`  ${fieldName}: ${defaultValue},\n`);
    }
    out.push("  _unrecognized: None,\n");
    out.push("}\n\n");

    out.push(`pub fn ${typeName}::default() -> ${typeName} {\n`);
    out.push(`  ${defaultVarName}\n`);
    out.push("}\n\n");
  }

  private writeEnum(record: RecordLocation, out: string[]): void {
    const variants = this.getPresentFields(record.record.fields);
    const typeName = this.getTypeName(record);
    const defaultVarName = `${typeName.toLowerCase()}__default`;

    out.push(`pub enum ${typeName} {\n`);
    const usedNames = new Set<string>();
    usedNames.add("Unknown");
    out.push("  Unknown(@client.UnrecognizedVariant)\n");
    for (const variant of variants) {
      const variantName = toEnumVariantName(variant.name.text, usedNames);
      usedNames.add(variantName);
      if (variant.type) {
        const variantType = this.typeSpeller.getMoonbitType(variant.type);
        out.push(`  ${variantName}(${variantType})\n`);
      } else {
        out.push(`  ${variantName}\n`);
      }
    }
    out.push("}\n\n");

    out.push(`let ${defaultVarName} : ${typeName} = `);
    out.push(
      `${typeName}::Unknown(@client.unrecognized_variant_default())\n\n`,
    );

    out.push(`pub fn ${typeName}::default() -> ${typeName} {\n`);
    out.push(`  ${defaultVarName}\n`);
    out.push("}\n\n");
  }

  private getPresentFields(fields: readonly Field[]): Field[] {
    return fields.filter((field) => field.name.text !== "removed");
  }

  private readonly typeSpeller: TypeSpeller;
}

export const GENERATOR = new MoonbitCodeGenerator();

function generateMoonPkg(module: Module): string {
  const imports: string[] = [];
  imports.push(`  "${CLIENT_PACKAGE_PATH}" @client,`);

  for (const [importedPath, importedNames] of Object.entries(
    module.pathToImportedNames,
  )) {
    if (!shouldImportModule(importedNames)) {
      continue;
    }
    const alias = modulePathToAlias(importedPath);
    const packageDir = modulePathToPackageDir(importedPath);
    imports.push(`  "${SKIROUT_PACKAGE_PREFIX}/${packageDir}" @${alias},`);
  }

  return `import {\n${imports.join("\n")}\n}\n`;
}

function shouldImportModule(importedNames: ImportedNames): boolean {
  return importedNames.kind === "all" || importedNames.names.size > 0;
}

const SKIROUT_PACKAGE_PREFIX = "skir/e2e-tests/skirout";
const CLIENT_PACKAGE_PATH = "skir/e2e-tests/client/types";
